<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\Item;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Items Controller
 *
 * @property \App\Model\Table\ItemsTable $Items
 */
class HomeController extends AppController
{

    public function index()
    {
        $options = [
            'limit' => 12,
            'order' => [
                'id' => 'desc'
            ]
        ];
        $itemsC = new ItemsController();

        $items = $this->paginate($itemsC->Items,$options);
        $this->set(compact('items'));
        $this->set('_serialize', ['items']);
    }

    function beforeFilter(Event $event)
    {
        $this->Auth->allow('index');
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


}
