<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\Item;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Items Controller
 *
 * @property \App\Model\Table\ItemsTable $Items
 */
class HomeController extends AppController
{

    public function beforeRender(Event $event)
    {
        $this->viewBuilder()->layout('default');
    }
    public function index()
    {
        $options = [
            'limit' => 12,
            'order' => [
                'id' => 'desc'
            ]

        ];
        $itemsC = new ItemsController();
        $items = $this->paginate($itemsC->Items,$options);

        foreach($items as $item){
            if(isset($item['promotionID'])){
                $item['itemPromotion'] = $itemsC->getItemPromotion($item['id']);
            }
        }


        $this->set(compact('items'));
        $this->set('_serialize', ['items']);
    }


    function onSubscribe(){
        include_once 'Component/MailchimpService.php';

        $service = new \MailchimpService();

        $data = [
            'email'     => $this->request->data['email'],
            'status'    => 'subscribed',
            'firstname' => $this->request->data['name'],
        ];
        $status = $service->addSubscriber($data);

        if($status !== 200){
            $this->Flash->error('Error Occurred');
            return $this->redirect('/');
        }else {
            $this->Flash->success('Subscribed');
            return $this->redirect('/');
        }

    }





    function setFlash($message = 'This is a flash'){
        $this->Flash->set($message);
        return $this->redirect('/');
    }

    function beforeFilter(Event $event)
    {
        $this->Auth->allow(['index', 'setFlash', 'onSubscribe']);
        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }



}
